### ISSUE TITLE
Request to add 4-bit AdamW

### ISSUE THREAD

**Issue by LiutongZhou** [kozistr/pytorch_optimizer#208]
## Paper and Code
Paper: [Memory Efficient Optimizers with 4-bit States](https://arxiv.org/abs/2309.01507)
Code : https://github.com/thu-ml/low-bit-optimizers/blob/main/lpmm/optim/optimizer.py

**Comment by kozistr** [comment]
thanks for the request! it requires cuda files to compile like `bitsandbytes` optimizer, so it's complicated to move entire implementations into this project, instead, maybe we can support the optimizer like this [example](https://github.com/huggingface/pytorch-image-models/blob/main/timm/optim/optim_factory.py#L262), that manually install or compile, and use it through `pytorch-optimizer`.

I'll figure it out how to smoothly support this in pytorch-optimizer :)

thank you!

**Comment by LiutongZhou** [comment]
Liked the idea of supporting it like the [example](https://github.com/huggingface/pytorch-image-models/blob/main/timm/optim/optim_factory.py#L262). 

Maybe even easier, make the FR to bnb and include it here?

**Comment by kozistr** [comment]
> Liked the idea of supporting it like the [example](https://github.com/huggingface/pytorch-image-models/blob/main/timm/optim/optim_factory.py#L262).
> 
> Maybe even easier, make the FR to bnb and include it here?
> 
> Made the FR to [TimDettmers/bitsandbytes#775](https://github.com/TimDettmers/bitsandbytes/issues/775)

that's a great idea! it'd be much better that bnb supports 4-bit optimizers

**Comment by kozistr** [comment]
@LiutongZhou hi! I came across that [torchao](https://github.com/pytorch/ao?tab=readme-ov-file#memory-efficient-optimizers) library supports 8/4bit, fp8 optimizers. still, they are pure Python implementations rather than custom CUDA kernels, I think using that library would be better than `lpmm` in terms of active maintenance, usability, and popularity.

if there's a better choice, I'll consider changing to another option later!
